title: Jerome Francis
email: francis.jerome999@gmail.com
author: Jerome Francis
github_username: jerryfrancis-97
url: "https://jerryfrancis-97.github.io"
baseurl: ""
permalink: /:year/:title/
google_analytics: UA-183805675-1

plugins:
  - jekyll-feed
  - jekyll-seo-tag

include: [_pages]
markdown: kramdown
kramdown:
  input: GFM
  parse_block_html: true

exclude:
  - vendor/
  - Gemfile.lock
  - "*.psd"
  - "*.zip"
